from decouple import config
from icecream import ic

DATABASE_HOSTNAME = config("DATABASE_HOSTNAME")
DATABASE_PORT = config("DATABASE_PORT")
DATABASE_PASSWORD = config("DATABASE_PASSWORD")
DATABASE_NAME = config("DATABASE_NAME")
DATABASE_USERNAME = config("DATABASE_USERNAME")
SECRET_KEY = config("SECRET_KEY") 
ALGORITHM = config("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = config("ACCESS_TOKEN_EXPIRE_MINUTES")

ic(DATABASE_HOSTNAME,DATABASE_PORT,DATABASE_NAME,ACCESS_TOKEN_EXPIRE_MINUTES)